name: Mert Kahyaoğlu
description: Personal Blog

footer-links:
  email: mertkahyaoglu93@gmail.com
  facebook: mertkahyaoglu48
  github: mertkahyaoglu
  twitter: mertkahyaoglu
  linkedin: mertkahyaoglu48

disqus: mertkahyaoglu
google_analytics: UA-63041764-1

url: http://mert-kahyaoglu.com
baseurl:

permalink: /:title/

version: v1.0.0

markdown: kramdown

sass:
  style: :expanded

plugins:
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
